name: Issue and Comment Monitor

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  show-issue-info:
    name: Show Issue Information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Issue Information
        id: extract_issue_info
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            echo "TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
            echo "BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
            echo "BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
          fi

     -  name: Print Issue Information
        run: |
          echo "Title: ${{ env.TITLE }}"
          echo "Body: ${{ env.BODY }}"
