name: Issue and Comment Monitor

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  show-issue-info:
    name: Show Issue Information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Issue Information
        id: extract_issue_info
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            TITLE="${{ github.event.issue.title }}"
            BODY="${{ github.event.issue.body }}"
          elif [ "${{ github.event_name }}" == "issue_comment" ]; then
            TITLE="${{ github.event.issue.title }}"
            BODY="${{ github.event.comment.body }}"
          fi
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "BODY=$BODY" >> $GITHUB_ENV
          ISSUE_CONTENT="Title:$TITLE\\nBody:$BODY"
          echo "ISSUE_CONTENT=$ISSUE_CONTENT" >> $GITHUB_ENV

      - name: Print Issue Information
        run: |
          echo "Title: ${{ env.TITLE }}"
          echo "Body: ${{ env.BODY }}"
          echo "Issue: ${{ env.ISSUE_CONTENT }}"
